-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(SALES_AMOUNT) * P.PRICE AS SALES
FROM PRODUCT P INNER JOIN OFFLINE_SALE O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE -- DISTINCT
ORDER BY SALES DESC, PRODUCT_CODE ASC; -- SALES 기준 정렬 후 PRODUCT_CODE 기준 정렬
