-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(30 * C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C 
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE AND DURATION_TYPE = '30일 이상'
    # JOIN 할 때 필요 없는 정보 삭제하기 
WHERE C.CAR_TYPE IN ('세단', 'SUV') 
AND C.CAR_ID NOT IN 
    (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    ) 
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC

    