-- 코드를 입력하세요
# SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES
# FROM REST_INFO
# GROUP BY FOOD_TYPE
# ORDER BY FOOD_TYPE DESC
# 여기서 REST_ID, REST_NAME을 최대 FAVORITES 튜플에 맞는 값을 출력해야 한다. 

# 그룹 내 여러 튜플 중 FAVORITES가 최대값을 가진 튜플 하나만 미리 중첩문으로 뽑아내기
SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
WHERE FAVORITES IN (SELECT MAX(FAVORITES)
                    FROM REST_INFO
                    GROUP BY FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC