-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, I.GENDER, COUNT(DISTINCT I.USER_ID) AS USERS
FROM USER_INFO I
    JOIN ONLINE_SALE S
    ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), I.GENDER
ORDER BY YEAR(SALES_DATE) ASC, MONTH(SALES_DATE) ASC, GENDER ASC