-- 코드를 입력하세요
SELECT ANIMAL_TYPE, Count(*) AS count
FROM ANIMAL_INS
WHERE (ANIMAL_TYPE LIKE 'Cat') OR (ANIMAL_TYPE LIKE 'Dog') -- 동물 종류가 개, 고양이 뿐이어서 없어도 괜찮음
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE ASC
