-- 코드를 입력하세요
SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%시트%' -- IN은 % 인식 불가, 순서 조심 OPTIONS가 먼저
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC
-- OPTIONS가 배열이 아니라 문자열이라는 점!
