SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
WHERE SKILL_CODE &
    (
        SELECT SUM(CODE) # 십진수 16 + 2048 + 8192 -> 이진수 1010000001000
        FROM SKILLCODES
        WHERE CATEGORY = 'Front End'
    )
ORDER BY ID ASC