-- 코드를 작성해주세요
SELECT COUNT(FISH_TYPE) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM (
        SELECT ID, FISH_TYPE,
            CASE
                WHEN LENGTH IS NULL THEN 10
                ELSE LENGTH END AS LENGTH,
                TIME
        FROM FISH_INFO
     ) FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE ASC